# Generated by Django 5.1.3 on 2025-11-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_conrextragmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_document', models.FileField(upload_to='pdf')),
                ('created', models.DateField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Файл PDF',
                'verbose_name_plural': 'Файлы PDF',
            },
        ),
        migrations.RenameModel(
            old_name='ConrextRAGModel',
            new_name='ContextRAGModel',
        ),
    ]
